apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  version: 2.15.1
  targetNamespace: cattle-system
  valuesContent: |
    hostname: rancher.k8s.orb.local
    replicas: 1
    ingress:
      tls:
        source: rancher
